#!/bin/bash
###############################################
#brief : auto create and debug
###############################################

file=`echo $1 | sed 's/\(.*\)\.\(.*\)/\1/'`
ext=`echo $1 | sed 's/.*\.\(.*\)/\1/'`

if [ ! -f $1 ]; then
        if [ $ext = "py" ]; then
            echo "#!/usr/bin/python " > $1
        elif [ $ext = "c" ]; then
            echo "#include<stdio.h>" >> $1
                echo -e "int main()\n{ \n\n} " >> $1
        elif [ $ext = "cpp" ]; then
            echo "#include<iostream>" >> $1
            echo "using namespace std;" >> $1
            echo -e "int main()\n{ \n\n} " >> $1
        else
            echo "#!/bin/bash" > $1
        fi
fi


while [ 1 ];
do
        vim $1
        chmod 755 $1
        if [ $ext = "java" ]; then
            javac $1
            [ $? -eq 0 ] && java $file
        elif [ $ext = "py" ]; then
            python $1
        elif [ $ext = "c" ]; then
            gcc $1
            [ $? -eq 0 ] && ./a.out
        elif [ $ext = "cpp" ]; then
            g++ -g $1
            [ $? -eq 0 ] && ./a.out
        else
            ./$1
        fi
        read dummy
done
